package bootstrap

import (
	"fmt"
	"strings"

	"github.com/anthropics/ferry/internal/registry"
)

// substituteVersion replaces {VERSION} in s with the given version string.
func substituteVersion(s, version string) string {
	return strings.ReplaceAll(s, "{VERSION}", version)
}

// GenerateEnvSh generates the content of ~/.ferry/env.sh for the given languages.
//
// Rather than appending PATH entries to ~/.zshrc on every install (which
// accumulates stale entries across version changes and is hard to clean up),
// ferry maintains a single file it owns completely. The shell RC gets one
// idempotent sourcing line; all runtime PATH setup lives here and is
// regenerated atomically on every bootstrap or update.
func GenerateEnvSh(langs []registry.ResolvedLanguage) string {
	var b strings.Builder
	b.WriteString("# Generated by ferry — do not edit.\n")
	b.WriteString("# Sourced from ~/.zshrc / ~/.bashrc via: . \"$HOME/.ferry/env.sh\"\n\n")

	for _, rl := range langs {
		if rl.Runtime == nil || len(rl.Runtime.ShellInit) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("# %s\n", rl.Language.Name))
		for _, line := range rl.Runtime.ShellInit {
			b.WriteString(substituteVersion(line, rl.Runtime.DefaultVersion) + "\n")
		}
		b.WriteString("\n")
	}
	return b.String()
}
